language: python
jobs:
  include:
  - os: linux
    dist: bionic
    python: 3.6
  - os: linux
    dist: bionic
    python: 3.7
  - os: linux
    dist: bionic
    python: 3.8
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.6
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.7
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.8
install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash -i install_macos.sh; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash -i install_linux.sh; fi
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- conda activate fish2eod
script:
- pytest
after_success:
- bash create_deploy.sh
env:
  global:
    secure: 1NKK0VPSp8MX4u+VS9i/iHRjJ4b08xeWqIlupLFGIyWy1LgPnpLQiol/N/o94aXbBf9VZ3UsgGK5hOuR7xeDjXFTu9Nd00A47uw4YlZxfWycirslNOYXgiFBqg1JvvF5jEKlOaPcdV5Ekm3c7Ly3PIS29E51PhmJi8lhHjPzApSwG7RqzoAN7t7kzLLlQJxLlv/cAjGLpoQ5fFMww4/fReoSgTWzox+1Y/aaozIa5VaWozXpl7Sc963SaxyjqX+tMRD2Bmxod1/3HIF3ijzjMpWz0uYNmrV4GaEVk8MEDpXp+ROL7R7lhJqQKES8GEei9vqcSi9vcMSA4yx/fLhpVdnSV6shLQYuDnpMpEjiiUeR8ddMpEwzrE1flPZqDH+OGJGK1ULIUSsYZpFkf15DCMCs6++E+9Edkmsjq+ElEYjxRklohXdCuYUJfFIIrPR3JrGqYo/aWzRuHp/bG2j9dnS4ns7F52HC6wqQv1sg5dR1wnXcfVddbL/D0N3Y0LCkGrmXHEYZAy/tV8be8oLx33zMlc82S5APYq8gU7tBSHSTmNpgnKEpImp0M0Mzj7HhuEF4GT3yTix7IQ3MuogVEiKvwSJnQQMm5BPpube5lZ1bs48witFPkdrgmch7d0Xuy29FA+H921VQoDhA71GQEUPdiOu9e3Fj7z8eOplp7Uo=
