language: python
jobs:
  include:
  - os: linux
    dist: bionic
    python: 3.6
  - os: linux
    dist: bionic
    python: 3.7
  - os: linux
    dist: bionic
    python: 3.8
  - os: linux
    dist: bionic
    python: 3.9
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.6
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.7
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.8
  - os: osx
    language: generic
    env: TRAVIS_PYTHON_VERSION=3.9
install:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then bash -i install_macos.sh; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then bash -i install_linux.sh; fi
- source "$HOME/miniconda/etc/profile.d/conda.sh"
- conda activate fish2eod
script:
- pytest
after_success:
- bash create_deploy.sh
env:
  global:
    secure: u8Lt0BIJahO1WNDpmoDkWAm9adnOluU5TzRanLGFjJFE5o336RJiJEyVYsE/ZZvnrR3cIrVEiQD7u8sML7FL2rOxFbDiRwwNWSGx/fQAeQsGtl1tO+ppiIphrqC0QKz2KvG/Q0hzZ0xXwc2Z6DP/BjNGxKGzHJoki2zptpHKQiFFnE8ZKMGnfFgcwafIujogxUBpcCswqg0DiPpqVcrnsAOxF1zZ1ZyqJQN4OjHvIqlc4naKtXT2FihemCFjhPZj8kYcqod0WlKRhg+kzmg4aDncfdBfaDMVnQYs/ZJOqTsPND+ZyODmCFnmMcsvzn+8GPuoICU69qtQNHwYRiEWGTL0O/BhBpTYvDhAUxr4OKoxF9A7KKM54WOSpdAnTcBxZRTvN8s1BCHI7fijqbNXFMyvXLmQV18c+SsXTNRPMMf+XaQ7mdRIV0WN9ZAU6dabY9sgxw7CVzTuYoii4p0IDv7zO30nNrIDINRTVrltr9toVr3FQqmUc7urQ8eFGOTHwsxgfvsO3nYQSaoccG3T9LhxJEu1+nHK5ySm89/zzta9FEKspD9Ki6ywhWRg7iqqcOQtWMHCzbQZD224nh0Sv63kd1YYKs9DsYHrRicSkb44EiHmR5IepyKWeX3LpjMHNLCZ0+7LMy5LvI6yyu+wh9Ij5Wz7cJGKHKu2fhhc1Lc=
