# conda env create -f conda_environment.yml
# conda env update --file conda_environment.yml --name ENV_NAME

name: fish2eod
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - fenics-dolfin==2019.1.0
  - pytest
  - pytest-runner
  - pytest-cov
  - pandas<1
  - tqdm
  - PyYAML
  - Sphinx>=2.0
  - Shapely
  - lxml
  - sphinx_rtd_theme
  - ipython
  - dataclasses
  - numpy
  - scipy
  - matplotlib
  - hypothesis
  - meshio
  - pip:
    - pygmsh==6.1.1 # pin to pre v7 TODO update to be compatible and update GMSH
    - opencv-python
    - tables
    - sphinx_autodoc_typehints
    - h5py --no-binary=h5py # conda or pip?